apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubeacademy.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: jenkins
  ports:
  - name: http
    port: 8080
    targetPort: http
    nodePort: {{ .Values.service.nodePort }}
